apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bhqqb224a-python 
  janus-idp.io/tekton: bhqqb224a-python
  backstage.io/kubernetes-id: bhqqb224a-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bhqqb224a-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  