apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bhqqb224a-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bhqqb224a-python 
  name: bhqqb224a-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bhqqb224a-python 
